# Weber function

# Current parameters that seem to work:
#   a       b                  c             biast             mu_p    mu_t    sdmu_p    sdmu_t   sex-limited p       sex-limited t
#  1         0.001             0.5            0.9             0.05    0.05    0.05        0.05        1                 1  
#Starting with various initial p values (p=3 for example)

#Parameters that work for multidimensional:

#parameter_object$a <- 1  
#parameter_object$b <- 0.001   
#parameter_object$c <- 0.5   # 0.2 might work better now!!!
#parameter_object$lambda <- 1  
#parameter_object$biast1 <- 0.9 
#parameter_object$biast2 <- 0.9
#parameter_object$mu_p1 <- 0.05
#parameter_object$mu_p2 <- 0.05
#parameter_object$mu_t1 <- 0.05
#parameter_object$mu_t2 <- 0.05
#parameter_object$sdmu_p1 <- 0.05
#parameter_object$sdmu_p2 <- 0.05
#parameter_object$sdmu_t1 <- 0.05
#parameter_object$sdmu_t2 <- 0.05
#parameter_object$sex_limited_p <- 1.0
#parameter_object$sex_limited_t <- 1.0
#parameter_object$pref_type <- 0
#parameter_object$web <- 0
#parameter_object$init_t1 <- 0
#parameter_object$init_t2 <- 0
#parameter_object$init_p1 <- 3
#parameter_object$init_p2 <- 3
#parameter_object$gam <- 2
#parameter_object$thet <- 1
